import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { FlureeClient, flureeConfig } from '@logosphere/fluree';
import {
  cardanoWalletConfig,
  CardanoWalletService,
  mintConfig,
  MintService,
  SubmitService,
  TransactionService,
} from '@logosphere/cardano';
import {
  WalletAssetFlureeRepository,
  WalletFlureeRepository,
  UserFlureeRepository,
  TrackFlureeRepository,
  ReorderpropsFlureeRepository,
  AlbumFlureeRepository,
  LikedTracksFlureeRepository,
  TrackHistoryFlureeRepository,
  MyTracksFlureeRepository,
} from './repositories/fluree';
import {
  WalletAssetResolver,
  WalletResolver,
  UserResolver,
  TrackResolver,
  ReorderpropsResolver,
  AlbumResolver,
  LikedTracksResolver,
  TrackHistoryResolver,
  MyTracksResolver,
} from './resolvers';
import {
  WalletAssetFlureeMap,
  WalletFlureeMap,
  UserFlureeMap,
  TrackFlureeMap,
  ReorderpropsFlureeMap,
  AlbumFlureeMap,
  LikedTracksFlureeMap,
  TrackHistoryFlureeMap,
  MyTracksFlureeMap,
} from './mappers/fluree';
import {
  WalletAssetDtoMap,
  WalletDtoMap,
  UserDtoMap,
  TrackDtoMap,
  ReorderpropsDtoMap,
  AlbumDtoMap,
  LikedTracksDtoMap,
  TrackHistoryDtoMap,
  MyTracksDtoMap,
} from './mappers/dto';

@Module({
  imports: [
    ConfigModule.forFeature(flureeConfig),
    ConfigModule.forFeature(mintConfig),
    ConfigModule.forFeature(cardanoWalletConfig),
  ],
  providers: [
    FlureeClient,
    CardanoWalletService,
    MintService,
    SubmitService,
    TransactionService,
    WalletAssetDtoMap,
    WalletDtoMap,
    UserDtoMap,
    TrackDtoMap,
    ReorderpropsDtoMap,
    AlbumDtoMap,
    LikedTracksDtoMap,
    TrackHistoryDtoMap,
    MyTracksDtoMap,
    WalletAssetFlureeMap,
    WalletFlureeMap,
    UserFlureeMap,
    TrackFlureeMap,
    ReorderpropsFlureeMap,
    AlbumFlureeMap,
    LikedTracksFlureeMap,
    TrackHistoryFlureeMap,
    MyTracksFlureeMap,
    WalletAssetFlureeRepository,
    WalletFlureeRepository,
    UserFlureeRepository,
    TrackFlureeRepository,
    ReorderpropsFlureeRepository,
    AlbumFlureeRepository,
    LikedTracksFlureeRepository,
    TrackHistoryFlureeRepository,
    MyTracksFlureeRepository,
    WalletAssetResolver,
    WalletResolver,
    UserResolver,
    TrackResolver,
    ReorderpropsResolver,
    AlbumResolver,
    LikedTracksResolver,
    TrackHistoryResolver,
    MyTracksResolver,
  ],
  exports: [],
})
export class ShankhnaadModule {}
